### ISSUE TITLE
provision-cluster - ImportError: cannot import name master_count

### ISSUE THREAD

**Issue by derdanu** [rcarmo/azure-docker-swarm-cluster#1]
dafalkne@MININT-9OT2MGI:~/git/azure-docker-swarm-cluster$ make provision-cluster
python provision-cluster.py
Traceback (most recent call last):
  File "provision-cluster.py", line 3, in <module>
    from utils import master_count, agent_count, master_pattern, agent_pattern, ssh, run
ImportError: cannot import name master_count
make: **\* [provision-cluster] Fehler 1

**Comment by rcarmo** [comment]
Ah. Apologies, I imported the wrong branch into GitHub (was looking at the original documentation branch alone), so the branch where the utility functions were consolidated wasn't merged.

(I couldn't import the original repo since that has proprietary code, so had to manually rebuild the repo)

Should be fixed now.
